import os

DEFAULT_CONFIG_DIR = "config"
MAIN_CONFIG_FILE = "MainConfig.xlsx"
EQUIPMENT_NORMALIZATION_SHEET = "Equipment_Normalization"
CALCULATION_RULES_FILE = "Calculation_Rules.xlsx"
MAIN_RULE_TABLE_FILE = "MainRuleTable.xlsx"
ECC_TEMPLATE_FILE = "ECC_Template.xlsx"
REFERENCE_SUBCON_REGION_FILE = "ReferenceSubconRegion.xlsx"

STATIC_CONFIG_FILES = [ECC_TEMPLATE_FILE, REFERENCE_SUBCON_REGION_FILE]

DEFAULT_MAIN_CONFIG_PATH = os.path.join(DEFAULT_CONFIG_DIR, MAIN_CONFIG_FILE)
DEFAULT_CALCULATION_RULES_PATH = os.path.join(DEFAULT_CONFIG_DIR, CALCULATION_RULES_FILE)
DEFAULT_MAIN_RULE_TABLE_PATH = os.path.join(DEFAULT_CONFIG_DIR, MAIN_RULE_TABLE_FILE)
DEFAULT_ECC_TEMPLATE_PATH = os.path.join(DEFAULT_CONFIG_DIR, ECC_TEMPLATE_FILE)
DEFAULT_REFERENCE_SUBCON_REGION_PATH = os.path.join(DEFAULT_CONFIG_DIR, REFERENCE_SUBCON_REGION_FILE)
